### ISSUE TITLE
Feature request: tab bar height

### ISSUE THREAD

**Issue by bbence84** [Afonsocraposo/buttons_tabbar#11]
Is it possible to expose parameters that would make it possible to specify the height of the tabbar? Thanks a lot! :)

**Comment by Afonsocraposo** [comment]
I'll work on it

**Comment by Afonsocraposo** [comment]
Done! https://github.com/Afonsocraposo/buttons_tabbar/commit/c9861f44a1852fb5567db943cd38fa4898b4988d
Change the `pubspec.yaml` to:
```dart
dependencies:
  ...
  buttons_tabbar: ^1.1.0
```

**Comment by bbence84** [comment]
@Afonsocraposo : thanks a lot, the height works! However there's no way to specify the Text font size. I can specify the icon size, that works, but the Text is just a string. I saw there's an optional child widget, but it does not seem to work for me (I provided a Text widget, but that does not show up at all). Thanks again for you lighting fast reaction! :)

**Comment by Afonsocraposo** [comment]
Thank you for raising this issues. I'll look into it

**Comment by Afonsocraposo** [comment]
Hey, fixed on https://github.com/Afonsocraposo/buttons_tabbar/commit/164da7bfcf860aacdbb618272dccfbd8e4170252
You can provide the Text font size with the `labelStyle` and `unselectedLabelStyle` parameters, or you can use the child widget of each `Tab`.
Don't forget to update your `pubspec.yaml` to:
```yaml
dependencies:
  ...
  buttons_tabbar: ^1.1.1
```
