### ISSUE TITLE
RTL animation

### ISSUE THREAD

**Issue by muhmmedAbdelkhalik** [Afonsocraposo/buttons_tabbar#13]
When I scrolling at rtl it happens like this
![2021-02-27 at 8 23 AM](https://user-images.githubusercontent.com/55117049/109377620-17f17780-78d5-11eb-8851-31c4a6fa0b1d.gif)

**Comment by Afonsocraposo** [comment]
Thank you for bringing this up. I'll look into it

**Comment by Afonsocraposo** [comment]
I was not able to reproduce your problem. Can you paste the code to do so? 
![output](https://user-images.githubusercontent.com/30601767/109390865-ff508400-790b-11eb-9bdc-5dd9c1ecbf66.gif)

**Comment by muhmmedAbdelkhalik** [comment]
Just try using it at RTL view it will happen

**Comment by muhmmedAbdelkhalik** [comment]
> I was not able to reproduce your problem. Can you paste the code to do so? 
> 
> ![output](https://user-images.githubusercontent.com/30601767/109390865-ff508400-790b-11eb-9bdc-5dd9c1ecbf66.gif)
> 
> 

Just try using it at RTL view it will happen

**Comment by Afonsocraposo** [comment]
Hi!
I fixed this problem https://github.com/Afonsocraposo/buttons_tabbar/commit/2e2d9a843114abda7228fcb3043fdae3741031ca .
Update your `pubspec.yaml` to use the new version `1.1.2`.
