### ISSUE TITLE
Use onTabChangedListener or similar

### ISSUE THREAD

**Issue by unidesigner** [Afonsocraposo/buttons_tabbar#15]
Hi, thanks for the package!

What is the correct way to provide a listener to buttons_tabbar that can change some other state? If I need to create a new controller, can you provide an example?

**Comment by Afonsocraposo** [comment]
Hi, I'm glad you like it!
Since `buttons_tabbar` works the same way as the native `TabBar` of Flutter, you can use it as described in the Flutter API:
https://api.flutter.dev/flutter/material/TabController-class.html

**Comment by unidesigner** [comment]
Thanks.
