### ISSUE TITLE
the example does not work

### ISSUE THREAD

**Issue by alandotic** [Afonsocraposo/buttons_tabbar#16]
running the example gave me the following message:
![image](https://user-images.githubusercontent.com/17924670/112747515-9c283f00-8fe8-11eb-810a-f251333b7173.png)

my flutter version:
`Flutter 2.0.2 • channel stable • https://github.com/flutter/flutter.git`
`Framework • revision 8962f6dc68 (2 weeks ago) • 2021-03-11 13:22:20 -0800`
`Engine • revision 5d8bf811b3`
`Tools • Dart 2.12.1`

**Comment by Afonsocraposo** [comment]
Thank you for bringing this up. I'll check it out

**Comment by alandotic** [comment]
@Afonsocraposo Hi i manage to figure out why the example code doesn't work in my project, it is because i have my TextButton ButtonStyle.minimumSize  =50 configured in the theme, is there any workaround for this?

**Comment by Afonsocraposo** [comment]
Hi, I fixed it https://github.com/Afonsocraposo/buttons_tabbar/commit/7fb09e04051a1f7c621d5e4344fc164228ffb608
Make sure to update the plugin version in `pubspec.yaml` to `1.2.1`  :)
