### ISSUE TITLE
How can i make selected color's gradient color ? is there no option for decoration

### ISSUE THREAD

**Issue by huseynovali** [Afonsocraposo/buttons_tabbar#17]

**Comment by Afonsocraposo** [comment]
There is no option to do that, but I will add it

**Comment by huseynovali** [comment]
Great news, we are waiting :)

**Comment by Afonsocraposo** [comment]
I'm sorry for the delay. I've been really busy. I'll try to push this update this weekend.

**Comment by Afonsocraposo** [comment]
Hi!
This was implemented in https://github.com/Afonsocraposo/buttons_tabbar/commit/2dc97a35ecfdb4fd12e9c8a5bd402f4631a42916
Use version `1.2.2` to unlock this new feature :)
