### ISSUE TITLE
can you add scrollable option? 

### ISSUE THREAD

**Issue by huseynovali** [Afonsocraposo/buttons_tabbar#18]
can you add a scrollable option?  like: https://stackoverflow.com/questions/54230115/horizontally-scrollable-tabs-focus-on-center-with-snap-in-flutter 

 isScrollable: true, or  isScrollable: false.

**Comment by Afonsocraposo** [comment]
Can you give some more details about what you mean?

**Comment by huseynovali** [comment]
I mean, in the default Tabbar when isScrollable: true active, the selected tab going to the center, and next tabs are visible, but in this package isn't like that

**Comment by huseynovali** [comment]
@Afonsocraposo didn't understand :/  ?

**Comment by huseynovali** [comment]
@Afonsocraposo  any improvement?

**Comment by Afonsocraposo** [comment]
Hi! I'm sorry for the delay. I've been really busy this past week. I'll try to push the update this weekend

**Comment by huseynovali** [comment]
thanks, i'm waiting

**Comment by Afonsocraposo** [comment]
Hi!
You can now (https://github.com/Afonsocraposo/buttons_tabbar/commit/5d81f759d99d36b644059833faee15258202ea52) choose to center the `TabBar` items by setting the option `center: true`.
To use this new feature, upgrade to version `1.3.0`.

**Comment by huseynovali** [comment]
@Afonsocraposo  unfortunately I didn't mean like that

<img width="396" alt="Screen Shot 2021-04-25 at 22 13 18" src="https://user-images.githubusercontent.com/49102327/116004466-caaf2f00-a613-11eb-844b-dcbd0b0dc589.png">

**Comment by huseynovali** [comment]
https://user-images.githubusercontent.com/49102327/116004540-2d082f80-a614-11eb-8fb1-93d3c0f3d88e.mov

i mean like this

**Comment by huseynovali** [comment]
I mean like this, can you please add this feature? thank you for your effort, I really appreciate

**Comment by Afonsocraposo** [comment]
![IMG_20210425_192012.jpg](https://user-images.githubusercontent.com/30601767/116004585-4f418380-a5fb-11eb-9465-946ddd9829c9.jpg)

Hello, this is what was illustrated in the post you mentioned. Please open a new issue explaining better what you asked for

**Comment by huseynovali** [comment]
the problem is the first tab beginning from center :/

**Comment by Afonsocraposo** [comment]
The video you sent is the default behavior of this package.

**Comment by huseynovali** [comment]
https://user-images.githubusercontent.com/49102327/116004721-0e566880-a615-11eb-8b0a-eb0c7a75f620.mov

**Comment by huseynovali** [comment]
> The video you sent is the default behavior of this package.

in this package have this problem in the video, the last item doesn't show all

**Comment by huseynovali** [comment]
i mean , the last item is not all visible

**Comment by Afonsocraposo** [comment]
Alright, I understood the problem. Can you open a new issue with that video and the code to recreate it?

**Comment by huseynovali** [comment]
okay
