### ISSUE TITLE
TabController dispose error

### ISSUE THREAD

**Issue by burakkurtarir** [Afonsocraposo/buttons_tabbar#2]
I'm getting this error A TabController was used after being disposed, when i leave from page.

**Comment by Afonsocraposo** [comment]
Can you give me more information? For example, how to recreate the problem? Can you also provide me the debug log?
Thank you!

**Comment by mohamedElsayed-Qtoof** [comment]
![image](https://user-images.githubusercontent.com/67856481/88641090-65033600-d0c7-11ea-9f6a-2d4fd1faeaa7.png)
the same probleam @Afonsocraposo

**Comment by Afonsocraposo** [comment]
Thank you for the screenshot @mohamedElsayed-Qtoof!
I'll try to reproduce the problem and fix it

**Comment by Afonsocraposo** [comment]
Thank you @burakkurtarir and @mohamedElsayed-Qtoof for bringing this problem into my attention. This bug has been fixed on commit https://github.com/Afonsocraposo/buttons_tabbar/commit/4ec81c876c85e726fb1f68b4320d57d980edc3e6.
You can also use the most recent version of this package by updating your `pubspec.yaml` to:
```yaml
dependencies:
  flutter:
    sdk: flutter
  buttons_tabbar: ^0.1.2+1
```
