### ISSUE TITLE
onTap function

### ISSUE THREAD

**Issue by sahmirzali** [Afonsocraposo/buttons_tabbar#22]
can you add to ButtonTabBar onTap functionality ?  for example onTap is have in TabBar

**Comment by Afonsocraposo** [comment]
Hi! 
Do you mean onTap on the Button?

**Comment by sahmirzali** [comment]
Yes

**Comment by Afonsocraposo** [comment]
Hello,

You can already do that using a `TabController`. Just attach a listener to it like so:
```dart
_tabController.addListener(() {
  print(_tabController.index);
});
```

**Comment by sahmirzali** [comment]
Thanks a lot man.!
