### ISSUE TITLE
built-in onTap function not available

### ISSUE THREAD

**Issue by LangRizkie** [Afonsocraposo/buttons_tabbar#23]
Hello, I see no onTap function on this lib, use .addListener doesn't work as expected and takes a lot of work for styling. I try to get a callback from the tab button tapped. thanks.

**Comment by Afonsocraposo** [comment]
Hi, sorry for the delay.
I added the `onTap` function in the latest commit https://github.com/Afonsocraposo/buttons_tabbar/commit/ad5efb5ec0461205de69cea92f04e46fb252c069. You can use the latest version of the package `1.3.1`.
Why do you say that `addListener` doesn't work as expected?
Can you also elaborate on why it takes a lot of work for styling and, if possible, give some suggestions for improvement?
Thanks!
