### ISSUE TITLE
How to add a shadow under the buttons?

### ISSUE THREAD

**Issue by HansCraftsman** [afonsocraposo/buttons_tabbar#25]
By adding a **BoxDecoration** property with a **BoxShadow** property, the shadow stays inside the button block and does not go outside of it. Is it possible to add a property like the **elevation** property to material objects?
`ButtonsTabBar(
              decoration: BoxDecoration(
                color: EtalogColors.primary,
                borderRadius: BorderRadius.circular(50),
                boxShadow:[
                  BoxShadow(
                    color: Colors.grey.withOpacity(0.5),
                    spreadRadius: 1,
                    blurRadius: 10,
                    offset: Offset(0, 15),
                  ),
                  //you can set more BoxShadow() here
                ],
              ),
            radius: 0,
            tabs: [
              Tab(text: 'Все'),
              Tab(text: 'В пути'),
              Tab(text: 'Под разгрузкой'),
            ],
          ),`

![image](https://user-images.githubusercontent.com/94063665/150775111-ae8a8434-a277-4b1c-89ff-db05eab6ddd8.png)

**Comment by afonsocraposo** [comment]
Hello, thank your for bringing this up. Would the option `elevation` fix your problem?

**Comment by HansCraftsman** [comment]
Hello, thanks for your response. If the buttons had an `elevation` property that works the same as the `Material` widgets, then this would solve my problem. Now the problem is that the container **around** the button limits the shadow of the button itself (this can be seen on the "Все" button).
So the `elevation` property is just a handy tool, but it won't work while there is a container constraint.
`BoxShadow` doesn't work for the same reason.

**Comment by afonsocraposo** [comment]
I added a new parameter for the `elevation`.
Let me know if it fixes your problem or not.
Nevertheless, feel free to reopen this issue :)

**Comment by afonsocraposo** [comment]
PS: use version `1.3.3`

**Comment by HansCraftsman** [comment]
Thanks for the quick solution.
The `elevation` property **completely solved** my problem.
Now another problem has appeared - before, the entire button block was aligned using the `alignment: Alignment.topCenter` property (the **first** screenshot in this thread), but now it ignores this property and is always pressed to the left edge of the screen.
![image](https://user-images.githubusercontent.com/94063665/151914265-642f8368-d160-4eb9-bee2-b27b776ae912.png)

The `center: true` property of **ButtonsTabBar** centers the first button, not the entire block of buttons.
![image](https://user-images.githubusercontent.com/94063665/151914367-602e6aaf-b357-49c0-ba59-8a6e20cfc2df.png)


Perhaps I don’t imagine the solution to this problem correctly, I didn’t try hard to figure it out, but I think other users will also change this behavior after upgrading to version 1.3.3 and they won’t find how to quickly fix it either. Was this behavior expected by you, or is it a bug?

**Comment by afonsocraposo** [comment]
This behavior was expected, but I changed the source code (version `1.3.4`), so you can obtain the effect you desire.
If you wrap the `ButtonsTabBar` widget with a `Center` widget, you can get the desired effect (without using the `center: true` parameter).
Let me know if it worked!

**Comment by HansCraftsman** [comment]
Good afternoon thanks! Everything is working great now!👍

**Comment by afonsocraposo** [comment]
Great! Thank you

**Comment by dipu0** [comment]
why Everything is not working for me!
