### ISSUE TITLE
[IMPROVEMENT] Border implementation

### ISSUE THREAD

**Issue by benoitr** [Afonsocraposo/buttons_tabbar#3]
Hi, It will be great if we can get border implemented in this package.

Use case example:

![unnamed](https://user-images.githubusercontent.com/205774/89557076-9049fb80-d812-11ea-8d58-8ad24091bc6f.jpg)

Maybe we could add something like this in the API:

ButtonsTabBar(
    borderWidth: 1.0,
    borderColor: Colors.blueAccent,
    unselectedBorderWidth: 1.0,
    unselectedborderColor: Colors.red,
)

Thanks for your consideration !

**Comment by Afonsocraposo** [comment]
Thank you for opening the issue. I'll try to have it working tomorrow!

**Comment by Afonsocraposo** [comment]
This feature was implemented on commit https://github.com/Afonsocraposo/buttons_tabbar/commit/b86d2b6278c0759ef28f4ee3c50c8f94e8af6075.
You can use the most recent version of this package by updating your `pubspec.yaml` to:
```yaml
dependencies:
  flutter:
    sdk: flutter
  buttons_tabbar: ^1.0.0+1
```
For help on how to use it, you can check the [`README.md`](https://github.com/Afonsocraposo/buttons_tabbar/blob/b86d2b6278c0759ef28f4ee3c50c8f94e8af6075/README.md) file.
