### ISSUE TITLE
如何获取currentIndex 

### ISSUE THREAD

**Issue by pen110** [afonsocraposo/buttons_tabbar#32]
如何获取currentIndex

**Comment by afonsocraposo** [comment]
Hi, can you ask this in english please?

**Comment by pen110** [comment]
oh, sorry.&nbsp;I wanna specify the index to jump,   like from index 1 to index 2. 




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "afonsocraposo/buttons_tabbar"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月13日(星期一) 晚上7:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [afonsocraposo/buttons_tabbar] 如何获取currentIndex  (Issue #32)





 
Hi, can you ask this in english please?

**Comment by afonsocraposo** [comment]
Hi @pen110.
Can you create a `TabController`, pass it to the `controller` attribute of `ButtonsTabBar` and then call the `animateTo` method of the `TabController`?
https://api.flutter.dev/flutter/material/TabController/animateTo.html

**Comment by pen110** [comment]
Yes, I did it like you said. It’s working! Thanks!



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Afonso Raposo ***@***.***&gt;
发送时间: 2023年3月15日 05:52
收件人: afonsocraposo/buttons_tabbar ***@***.***&gt;
抄送: Pen ***@***.***&gt;, Mention ***@***.***&gt;
主题: Re: [afonsocraposo/buttons_tabbar] 如何获取currentIndex  (Issue #32)

**Comment by afonsocraposo** [comment]
Perfect! I'm glad it worked
