### ISSUE TITLE
Allow ButtonsTabBar to take the whole width in case of no scroll

### ISSUE THREAD

**Issue by realitymolder** [afonsocraposo/buttons_tabbar#37]
# Bug Report

## Description

When the list is short and not scrollable, ButtonsTabBar isn't taking the whole horizontal space of the screen. I would suggest having a boolean that will help us achieve it.

Example: 
 
![image](https://github.com/afonsocraposo/buttons_tabbar/assets/26459151/23201b0d-3d1b-415c-a645-f6095bb27b25)

**Comment by afonsocraposo** [comment]
Hey @realitymolder !
What do you mean? Do you mean that the buttons should expand to fill the whole horizontal space of the screen?

**Comment by realitymolder** [comment]
> Hey @realitymolder ! What do you mean? Do you mean that the buttons should expand to fill the whole horizontal space of the screen?

Hey there, yes! Maybe as a flag (bool) we can have this feature that as long as the list isn't scrolling (beyond the size of the screen) it should stretch each button. Like here: 
as you can see there are 2 items, so it divides each item to 50% of the screen. 
![telegram-cloud-photo-size-4-5864223375751233512-x](https://github.com/afonsocraposo/buttons_tabbar/assets/26459151/5034d613-53f5-4fa8-b7d2-97d2100f3904)

**Comment by afonsocraposo** [comment]
Hey @realitymolder! I understand now.
I'm sorry, but I won't implement this feature, since it doesn't align with the purpose of this package.
I hope you can understand 🙏🏻

**Comment by dipu0** [comment]
there is two button and i want to fill screen width with btns but here i can not!

**Comment by afonsocraposo** [comment]
Hi @dipu0 !
Thank you for sharing your interest in this package. I'm sorry, but, as I mentioned above, this feature doesn't align with the purpose of this package

**Comment by dipu0** [comment]
> Hi @dipu0 !
> Thank you for sharing your interest in this package. I'm sorry, but, as I mentioned above, this feature doesn't align with the purpose of this package

But when using two or three buttons and no scroll, there should be an option to expand and take the full screen width. I am using both scroll (multiple buttons with scroll) and only three with no scroll. Now I need another feature that will examine two buttons. I don't know why this isn't aligned with your purpose! And it is too disappointing that you are not willing to extend a feature that requires multiple users. And now I'm afraid of using this in the production level app.
