### ISSUE TITLE
The problem is that there are many titles, such as Title 1, Title 222, title 33333，One of my requirements is to keep the length of each title consistent, consistent design style.

### ISSUE THREAD

**Issue by pen110** [afonsocraposo/buttons_tabbar#41]
The problem is that there are many titles, such as Title 1, Title 222, title 33333，One of my requirements is to keep the length of each title consistent, consistent design style.
<img width="849" alt="image" src="https://github.com/afonsocraposo/buttons_tabbar/assets/7963859/d3e9bee3-531a-4ab6-8705-3751a57ef600">

like this image, every single title has same length. But in my project, they are different length.

**Comment by afonsocraposo** [comment]
Hey @pen110 !
Sorry for the long delay...
Can you please provide the code used on your project?

**Comment by afonsocraposo** [comment]
https://github.com/afonsocraposo/buttons_tabbar/issues/45
