### ISSUE TITLE
Enable onSwipe callback to update TabView dynamically when tab is changed by Swipe not by Button

### ISSUE THREAD

**Issue by MennaCC** [afonsocraposo/buttons_tabbar#46]
# Feature Request

## Description

Need to set "onSwipe" callback in TabBarView paramaters like setting "onTap" to buttonsBar, so I can call an async function to update the view dynamically

**Comment by afonsocraposo** [comment]
Hi @MennaCC , I'm sorry for the delay on this.
You can already achieve this behavior by adding a listener to the `TabController`:
```dart
TabController tabController = TabController(
  length: 2,
  vsync: this,
  initialIndex: transactionTypeToIndex(
    transactionsScreenTypeProvider.type,
  ),
);
tabController.addListener(onTabChanged);
```
Where `onTabChanged` is something like:
```dart
onTabChanged() {
  if (tabController.indexIsChanging) return;
  switch (tabController.index) {
    case 0:
      // do something
      break;
    case 1:
      // do something
      break;
  }
}
```

**Comment by MennaCC** [comment]
> Hi @MennaCC , I'm sorry for the delay on this. You can already achieve this behavior by adding a listener to the `TabController`:
> 
> ```dart
> TabController tabController = TabController(
>   length: 2,
> );
> tabController.addListener(onTabChanged);
> ```
> 
> Where `onTabChanged` is something like:
> 
> ```dart
> onTabChanged() {
>   if (tabController.indexIsChanging) return;
>   switch (tabController.index) {
>     case 0:
>       // do something
>       break;
>     case 1:
>       // do something
>       break;
>   }
> }
> ```
I think that the expected default behavior for the already implemented onTap function is to change the view whether it is tapped or swiped since the swipe detection is already implemented (thank you for that btw) .
Instead of tampering with the already implemented onTap I just made the onSwipe and used it instead of the onTap.

I think it is always better to encapsulate all the controller and addListener stuff inside the package itself for its user (like what's done in the onTap), and much simpler to use especially if the views change dynamically due to the object I associate with the tab.

**Comment by afonsocraposo** [comment]
Thank you for the explanation @MennaCC . That's a fair point, let's merge the PR you worked on

**Comment by afonsocraposo** [comment]
Thank you for the explanation @MennaCC . That's a fair point, however, after inspecting Flutter's default TabBar implementation:

https://api.flutter.dev/flutter/material/TabBar/onTap.html

I noticed that only the onTap method is provided. Which I assume it is because it is difficult to distinguish between onTap and onSwipe gestures from the TabBar itself.

Therefore, I'll keep this package as it is. I'm sorry and I hope you understand.

**Comment by MennaCC** [comment]
can you at least add the modifocation to the onTap?

**Comment by afonsocraposo** [comment]
Hey @MennaCC!

In Flutter's documentation, it says that the `onTap` method for `TabBar` is:
> An optional callback that's called when the [TabBar](https://api.flutter.dev/flutter/material/TabBar-class.html) is tapped.
The callback is applied to the index of the tab where the tap occurred.

I believe the implementation in `ButtonsTabBar` the `onTap` callback does the same, no?

Can you elaborate what behavior you are expecting from the `onTap` callback?

**Comment by MennaCC** [comment]
im expecting that the behavior i set for the onTap happens on "index change" by either tap or swipe.

**Comment by afonsocraposo** [comment]
Hi @MennaCC! I think it's better to keep the `onTap` behavior similar to what Flutter provides on the native `TabBar`:
https://api.flutter.dev/flutter/material/TabBar/onTap.html

**Comment by dipu0** [comment]
i also need onSwipe callback ;(

**Comment by afonsocraposo** [comment]
Hey @dipu0!
Please find the answer to your problem here:
https://stackoverflow.com/questions/55485466/how-to-detect-tabbar-change-in-flutter
