### ISSUE TITLE
Generate tab list dynamically, when touch tab return issue 

### ISSUE THREAD

**Issue by whatamelon** [Afonsocraposo/buttons_tabbar#5]
When I generate tab like this,

```
   List<Tab> _pickys = <Tab>[];

   for(int i = 0; i < _nitemPicky.length; i++) {
    _pickys.add(
       Tab(
         icon: Image.network('$img_url${_nitemPicky[i].imgLinkTb}', width: Du.mw(30), height: Du.mw(30),),
         text: "${_nitemPicky[i].name}",
       ),
     );
   }
```

or like this,

```
   List<Tab> _pickys2 = List<Tab>.generate(_nitemPicky.length, (int index3) {
     print(_nitemPicky[index3]);
     return new Tab(
       icon: Image.network('$img_url${_nitemPicky[index3].imgLinkTb}', width: Du.mw(30), height: Du.mw(30),),
       text: "${_nitemPicky[index3].name}",
     );
   });
```

Generate tab is good. 

But when I touch list[1] to list[2]

tapping gonna failed and returned this issue.

I/flutter ( 2283): ══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
I/flutter ( 2283): The following NoSuchMethodError was thrown while handling a gesture:
I/flutter ( 2283): The method 'findRenderObject' was called on null.
I/flutter ( 2283): Receiver: null
I/flutter ( 2283): Tried calling: findRenderObject()
I/flutter ( 2283): 
I/flutter ( 2283): When the exception was thrown, this was the stack:
I/flutter ( 2283): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
I/flutter ( 2283): #1      _ButtonsTabBarState._scrollTo (package:buttons_tabbar/buttons_tabbar.dart:378:48)
I/flutter ( 2283): #2      _ButtonsTabBarState._setCurrentIndex.<anonymous closure> (package:buttons_tabbar/buttons_tabbar.dart:336:7)
I/flutter ( 2283): #3      State.setState (package:flutter/src/widgets/framework.dart:1240:30)
I/flutter ( 2283): #4      _ButtonsTabBarState._setCurrentIndex (package:buttons_tabbar/buttons_tabbar.dart:332:5)
I/flutter ( 2283): #5      _ButtonsTabBarState._goToIndex (package:buttons_tabbar/buttons_tabbar.dart:326:7)
I/flutter ( 2283): #6      _ButtonsTabBarState._buildButton.<anonymous closure> (package:buttons_tabbar/buttons_tabbar.dart:255:11)
I/flutter ( 2283): #7      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:992:19)
I/flutter ( 2283): #8      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:1098:38)
I/flutter ( 2283): #9      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:184:24)
I/flutter ( 2283): #10     TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:524:11)
I/flutter ( 2283): #11     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:284:5)
I/flutter ( 2283): #12     BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:256:7)
I/flutter ( 2283): #13     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:158:27)
I/flutter ( 2283): #14     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:224:20)
I/flutter ( 2283): #15     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:200:22)
I/flutter ( 2283): #16     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:158:7)
I/flutter ( 2283): #17     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:104:7)
I/flutter ( 2283): #18     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:88:7)
I/flutter ( 2283): #22     _invoke1 (dart:ui/hooks.dart:267:10)
I/flutter ( 2283): #23     _dispatchPointerDataPacket (dart:ui/hooks.dart:176:5)
I/flutter ( 2283): (elided 3 frames from dart:async)
I/flutter ( 2283): 
I/flutter ( 2283): Handler: "onTap"
I/flutter ( 2283): Recognizer:
I/flutter ( 2283):   TapGestureRecognizer#fbbeb
I/flutter ( 2283): ════════════════════════════════════════════════════════════════════════════════════════════════════

Also, when I generate list statically, 
like this.

```
    List<Tab> tabs = <Tab>[
    Tab(
      icon: Image.asset('assets/circle_you.png', width: Du.mw(30), height: Du.mw(30),),
      text: "김꽃날",
    ),
    Tab(
      icon: Image.asset('assets/circle_you.png', width: Du.mw(30), height: Du.mw(30),),
      text: "하티",
    ),
    Tab(
      icon: Image.asset('assets/circle_you.png', width: Du.mw(30), height: Du.mw(30),),
      text: "오구리",
    ),
    Tab(
      icon: Image.asset('assets/circle_you.png', width: Du.mw(30), height: Du.mw(30),),
      text: "민주티디",
    ),
    Tab(
      icon: Image.asset('assets/circle_you.png', width: Du.mw(30), height: Du.mw(30),),
      text: "옥개",
    ),
    Tab(
      icon: Image.asset('assets/circle_you.png', width: Du.mw(30), height: Du.mw(30),),
      text: "지토",
    ),
  ];

```

No error returned and working properly.

So, I want generate list dynamically.

How can I implement?

**Comment by Afonsocraposo** [comment]
Thank you for pointing this in such a detailed way! I'll look into it and try to reproduce and fix the issue @whatamelon

**Comment by Afonsocraposo** [comment]
Sorry for the delay, @whatamelon 
I tried to reproduce your problem, but wasn't able to do so. The following example generates a list dynamically and is working well. Can you test with the below code or provide more details about your problem?

```dart
class Example extends StatefulWidget {
  Example({Key key}) : super(key: key);

  @override
  _ExampleState createState() => _ExampleState();
}

class _ExampleState extends State<Example> {
  int length = 3;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SafeArea(
        child: DefaultTabController(
          length: length,
          child: Column(
            children: <Widget>[
              ButtonsTabBar(
                tabs: List<Tab>.generate(
                  length,
                  (int index) => Tab(
                    text: "$index",
                  ),
                ),
              ),
              Expanded(
                child: TabBarView(
                  children: List.generate(
                    length,
                    (int index) => Center(
                      child: Text("$index"),
                    ),
                  ),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
```

The above code generates the tab and children widgets every time the app rebuilds, which is not advised for performance. The tab list and its children can be dynamically generated in `initState`:
```dart
class Example extends StatefulWidget {
  Example({Key key}) : super(key: key);

  @override
  _ExampleState createState() => _ExampleState();
}

class _ExampleState extends State<Example> {
  int length = 3;
  List<Tab> tabs;
  List<Widget> children;

  @override
  void initState() {
    super.initState();
    tabs = List<Tab>.generate(
      length,
      (int index) => Tab(
        text: "$index",
      ),
    );
    children = List.generate(
      length,
      (int index) => Center(
        child: Text("$index"),
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SafeArea(
        child: DefaultTabController(
          length: length,
          child: Column(
            children: <Widget>[
              ButtonsTabBar(
                tabs: tabs,
              ),
              Expanded(
                child: TabBarView(
                  children: children,
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
```

**Comment by whatamelon** [comment]
@Afonsocraposo , Thanks for your try. Well, I'm wrap build method futurebuilder.
I think, that point can be produce issue. 
Can you check with futurebuilder?

**Comment by Afonsocraposo** [comment]
@whatamelon can you share the code to reproduce this error?

**Comment by whatamelon** [comment]
Well, this is code that produce issue.
Hope it help for you. XD


import 'dart:async';
import 'dart:core';

import 'package:buttons_tabbar/buttons_tabbar.dart';
import 'package:cached_network_image/cached_network_image.dart';
import 'package:fitchoo/analytics/am.dart';
import 'package:fitchoo/pages/shop/beforeOrderInfo.dart';
import 'package:fitchoo/pages/shop/cartPage.dart';
import 'package:fitchoo/pages/shop/choiceOption.dart';
import 'package:fitchoo/pages/shop/itemQuestion.dart';
import 'package:fitchoo/states/purchase_state.dart';
import 'package:fitchoo/states/user_state.dart';
import 'package:fitchoo/utils/designUtil.dart';
import 'package:fitchoo/utils/fixPrice.dart';
import 'package:fitchoo/utils/textStyle.dart';
import 'package:flutter/material.dart';
import 'package:flutter/widgets.dart';
import 'package:flutter_conditional_rendering/flutter_conditional_rendering.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:provider/provider.dart';



class ItemDetailPage extends StatefulWidget {
  final String id;
  final String click;

  ItemDetailPage({Key key, this.id, this.click}) : super(key: key);
  @override
  _ItemDetailPageState createState() => _ItemDetailPageState();
}

class _ItemDetailPageState extends State<ItemDetailPage> with SingleTickerProviderStateMixin {

  TabController _tabController;
  final ScrollController _allscrollController = new ScrollController();
  final tabKey = new GlobalKey();

  bool _once = true;

  bool _expand = false;

 @override
  void initState() {
    super.initState();
    PurchaseState $purchase = Provider.of<PurchaseState>(context, listen: false);
    Am.ampt.logEvent('/pageview_dealPick', eventProperties: {'dItemName': '${$purchase.neoitemName}'});
    Am.ampt.uploadEvents();
    UserState $user = Provider.of<UserState>(context, listen: false);

    _tabController = TabController(vsync: this, length: tabs.length);

    _tabController.addListener(() async{
      setState(() {
        _expand = false;
      });
      Scrollable.ensureVisible(tabKey.currentContext);
    });
  }

  double mw(i) {
    ScreenUtil.init(width: 360, height: 640, allowFontScaling: true);
    return i * ScreenUtil().scaleWidth;
  }

  String modifyDate(i) {
    print(i);
    if(i == null || i == '') {
      return i;
    } else {
      return i.substring(0,16).replaceAll(new RegExp(r'-'),'.');
    }
  }

  @override
  void dispose() {
    _allscrollController.dispose();
    _tabController.dispose();
    super.dispose();
  }


  Future<bool> _onBackPressed() async{
    PurchaseState $purchase = Provider.of<PurchaseState>(context, listen: false);
    $purchase.resetQnaList();
    $purchase.resetPickyList();
    Navigator.pop(context);
  }


  @override
  Widget build(BuildContext context) {
    PurchaseState $purchase = Provider.of<PurchaseState>(context);
    UserState $user = Provider.of<UserState>(context);
    final String img_url = "http://s3.ap-northeast-2.amazonaws.com/image.fitchoo";

    return WillPopScope(
      onWillPop: _onBackPressed,
      child: SafeArea(
        top: true,
        child: Scaffold(

            floatingActionButtonLocation: FloatingActionButtonLocation.endFloat,
              floatingActionButton: Stack(
                children: [
                  Positioned(
                    right:mw(0),
                    bottom: mw(60),
                    child: Container(
                      decoration: BoxDecoration(
                          borderRadius: BorderRadius.all(Radius.circular(100)),
                          border: Border.all(color: Du.darkGrey(), width: mw(2))
                      ),
                      width: mw(35),
                      height: mw(35),
                      child: Align(
                        alignment: Alignment.bottomRight,
                        child: FloatingActionButton(
                          backgroundColor: Colors.white,
                          heroTag: 'itemPageHeroUpButton${widget.id}',
                          elevation: 1,
                          onPressed: () {
                            _allscrollController.animateTo(0, duration: Duration(milliseconds: 500), curve: Curves.fastOutSlowIn);
                          },
                          child: Icon(Icons.keyboard_arrow_up, color: Colors.black, size: mw(25),),
                        ),
                      ),
                    ),
                  ),
                  Positioned(
                    left: mw(28),
                    bottom: mw(5),
                    child: Align(
                      alignment: Alignment.bottomCenter,
                      child: AbsorbPointer(
                        absorbing: !_once,
                        child: Container(
                          width:mw(332), height:mw(45),
                          child: FloatingActionButton(
                            heroTag: 'itemPageGoToBuyButton${widget.id}',
                            elevation: 1,
                            backgroundColor: $purchase.priceClass == '9' ? Color(0XFF8a8a8a) : Colors.black,
                            shape: RoundedRectangleBorder(
                                borderRadius: BorderRadius.all(Radius.circular(5))
                            ),
                            onPressed: () async{
                              if(_once) {
                                _once = false;
                                Am.ampt.logEvent('click_order',
                                    eventProperties: {'dItemName': '${$purchase.neoitemName}', 'clickedPage': 'dealPick', 'pickyName':''});
                                await $purchase.getOptions($user.accessToken, $user.appInfo, widget.id, 'root');
                                $purchase.priceClass == '9' ? print('dd') :
                                Navigator.push(context,MaterialPageRoute(builder: (context) => ChoiceOptionPage()));
                                _once = true;
                              }
                            },
                            child: Center(child: Text( $purchase.priceClass == '9' ?  '판매중지' : '구매하기', style: Ts.btwr())),
                          ),
                        ),
                      ),
                    ),
                  ),
                ],
              ),
              backgroundColor: Colors.white,
              body: _buildBody(context,$purchase,img_url, $user),
            ),
      ),
    );
  }


 Widget _buildBody(context,$purchase,img_url, $user) {

   List<Tab> tabs = List<Tab>.generate(_nitemPicky.length, (int index3) {
     print(_nitemPicky[index3]);
     return new Tab(
       icon: Image.network('$img_url${_nitemPicky[index3].imgLinkTb}', width: Du.mw(30), height: Du.mw(30),),
       text: "${_nitemPicky[index3].name}",
     );
   });
    return CustomScrollView(
        controller: _allscrollController,
        slivers: [
            SliverAppBar(
              primary:true,
              floating: true,
              flexibleSpace: Container(),
              leading: new IconButton(
                  icon: new Icon(Icons.arrow_back_ios, color: Colors.black, size:22.w),
                  onPressed: () => _onBackPressed()
              ),
              actions: [
                IconButton(
                  icon: Icon(Icons.shopping_cart, color: Colors.black, size: 22.w,),
                  onPressed: () {
                    Navigator.push(context,MaterialPageRoute(builder: (context) => CartPage()));
                  }
                )
              ],
              title: Text(
                  $purchase.neoitemName,
                  style: Ts.h3bm()
              ),
              centerTitle: true,
              elevation: 1,
            ),
            SliverToBoxAdapter(
              child: Column(
                mainAxisAlignment: MainAxisAlignment.start,
                crossAxisAlignment: CrossAxisAlignment.start,
                children: <Widget>[
                  CachedNetworkImage(
                    fadeInCurve: Curves.fastOutSlowIn,
                    fadeInDuration: Duration(seconds: 1),
                    fit: BoxFit.cover,
                    width:mw(360),
                    height:mw(360),
                    imageUrl: '$img_url${$purchase.neoimgLink}',
                    placeholder: (context, url) => Container(
                      width:mw(360),
                      height:mw(360),
                      color:Color(0XFFececec)
                    ),
                    errorWidget: (context, url, error) => Container(
                      width:mw(360),
                      height:mw(360),
                      color:Color(0XFFececec),
                      child: Center(child: Image.asset('assets/p_logo.png', width: mw(360), height: mw(360))),
                    ),
                  ),
                  SizedBox(height: mw(12),),
                  $purchase.priceClass == '9'?
                  Container(
                    width: mw(332),
                    height: mw(22),
                    padding: EdgeInsets.symmetric(horizontal: mw(14)),
                    child: Row(
                      mainAxisAlignment: MainAxisAlignment.start,
                      crossAxisAlignment: CrossAxisAlignment.end,
                      children: <Widget>[
                        Container(
                          color: Color(0XFF8a8a8a),
                          width:mw(57),
                          height:mw(22),
                          padding: EdgeInsets.symmetric(horizontal: mw(6), vertical: mw(2)),
                          child: Text('판매종료', style:Ts.stwr()),
                        ),
                        SizedBox(width: mw(10),),
                        Text($purchase.neoitemName, style: Ts.h2bb(),),
                      ],
                    ),
                  ):
                  Padding(
                    padding: EdgeInsets.symmetric(horizontal: mw(14)),
                    child: Text($purchase.neoitemName, style: Ts.h2bb(),),
                  ),
                  SizedBox(height: mw(3),),
                  $purchase.priceClass == '1' || $purchase.priceClass == '2'?
                  Container(
                    width: mw(332),
                    height: mw(33),
                    padding: EdgeInsets.symmetric(horizontal: mw(14)),
                    child: Row(
                      mainAxisAlignment: MainAxisAlignment.start,
                      crossAxisAlignment: CrossAxisAlignment.end,
                      children: <Widget>[
                        Text('${$purchase.saleRatio}%', style: TextStyle(fontSize: ScreenUtil().setSp(22), fontWeight: FontWeight.w800, color: Du.primary()),),
                        SizedBox(width: mw(10),),
                        Text(FixPrice.fixPrice($purchase.priceChg), style: Ts.h1bb(),),
                        SizedBox(width: mw(8),),
                        Padding(
                          padding: EdgeInsets.only(bottom: mw(3)),
                          child: Text(FixPrice.fixPrice($purchase.price), style: TextStyle(color: Du.grey(), fontSize: Du.fs(14), fontWeight: Du.fw(4),decoration: TextDecoration.lineThrough))),
                      ],
                    ),
                  ): Padding(
                    padding: EdgeInsets.symmetric(horizontal: mw(14)),
                    child :Text(FixPrice.fixPrice($purchase.price), style: Ts.h1bb(),),
                  ),
                  SizedBox(height: mw(14),),
                  Container(
                    width: mw(360),
                    height: mw(32),
                    child: Row(
                      children: <Widget>[
                        Align(
                          alignment: Alignment.centerLeft,
                          child: ListView.builder(
                              padding: EdgeInsets.only(left: mw(20), right:mw(10)),
                              physics: NeverScrollableScrollPhysics(),
                              scrollDirection: Axis.horizontal,
                              shrinkWrap: true,
                              reverse: true,
                              itemCount: $purchase.pcList.length-1 > 5 ? 5 : $purchase.pcList.length,
                              itemBuilder: (context, i) {
                                return
                                  $purchase.pcList.length-1 < 5 ?
                                  Align(
                                  widthFactor: 0.7,
                                  child: ClipOval(
                                    child:
                                    CachedNetworkImage(
                                      fadeInCurve: Curves.fastOutSlowIn,
                                      fadeInDuration: Duration(seconds: 1),
                                      fit: BoxFit.cover,
                                      width:mw(32),
                                      height:mw(32),
                                      imageUrl: '$img_url${$purchase.pcList[i].imgLinkTb}',
                                      placeholder: (context, url) => Container(
                                          width:mw(32),
                                          height:mw(32),
                                          color:Color(0XFFececec)
                                      ),
                                      errorWidget: (context, url, error) => Container(
                                        width:mw(32),
                                        height:mw(32),
                                        color:Color(0XFFececec),
                                        child: Center(child: Image.asset('assets/p_logo.png', width: mw(32), height: mw(32))),
                                      ),
                                    ),
                                  ),
                                ): i != 0 ?
                                  Align(
                                    widthFactor: 0.7,
                                    child: ClipOval(
                                      child:
                                      CachedNetworkImage(
                                        fadeInCurve: Curves.fastOutSlowIn,
                                        fadeInDuration: Duration(seconds: 1),
                                        fit: BoxFit.cover,
                                        width:mw(32),
                                        height:mw(32),
                                        imageUrl: '$img_url${$purchase.pcList[i].imgLinkTb}',
                                        placeholder: (context, url) => Container(
                                            width:mw(32),
                                            height:mw(32),
                                            color:Color(0XFFececec)
                                        ),
                                        errorWidget: (context, url, error) => Container(
                                          width:mw(32),
                                          height:mw(32),
                                          color:Color(0XFFececec),
                                          child: Center(child: Image.asset('assets/p_logo.png', width: mw(32), height: mw(32))),
                                        ),
                                      ),
                                    ),
                                  ): Align(
                                    widthFactor: 0.7,
                                    child: ClipOval(
                                      child: Container(
                                        width: mw(32),
                                        height: mw(32),
                                        color: Color(0XFFbbbbbb),
                                        child: Icon(Icons.more_horiz, size: mw(15), color: Colors.white,),
                                      ),
                                    ),
                                  );
                              }
                          ),
                        ),
                        Container(
                          height: mw(32),
                          child: Row(
                            crossAxisAlignment: CrossAxisAlignment.end,
                            children: <Widget>[
                              Text('${$purchase.pcList.length}', style: TextStyle(fontWeight: FontWeight.w800, fontSize: ScreenUtil().setSp(12), color: Colors.black),),
                              Text('명 참여중', style: Ts.st1br()),
                            ],
                          ),
                        ),
                      ],
                    ),
                  ),
                  SizedBox(height: mw(10),),
                  Row(
                    mainAxisAlignment: MainAxisAlignment.start,
                    children: [
                      SizedBox(width: mw(14),),
                      Text('배송비', style: Ts.bd1dgr(),),
                      SizedBox(width: mw(76),),
                      Text('2,500원', style: Ts.bd1br(),),
                    ],
                  ),
                  SizedBox(height: mw(5),),
                  Row(
                    mainAxisAlignment: MainAxisAlignment.start,
                    children: [
                      SizedBox(width: mw(14),),
                      Image.asset('assets/blackbackP.png', width: mw(20), height: mw(20),),
                      SizedBox(width: mw(5),),
                      Text('적립포인트', style: Ts.bd1dgr(),),
                      SizedBox(width: mw(25),),
                      Text('270원', style: Ts.bd1br(),),
                    ],
                  ),
                  SizedBox(height: mw(21),),
                  Container(
                    height:mw(40),
                    child: ListView.builder(
                        padding: EdgeInsets.only(left: mw(11.5)),
                        scrollDirection: Axis.horizontal,
                        shrinkWrap: true,
                        itemCount: $purchase.neotagList.length,
                        itemBuilder: (BuildContext context, int index) {
                          return Container(
                            margin: EdgeInsets.symmetric(horizontal: mw(2.5)),
                            child: Chip(
                              padding: EdgeInsets.fromLTRB(mw(10), mw(6), mw(10),mw(6)),
                              backgroundColor: Color(0XFFf2f2f2),
                              label: Text('#${$purchase.neotagList[index]}', style: Ts.st1br()),
                              shape: RoundedRectangleBorder(borderRadius: BorderRadius.all(Radius.circular(15))),
                            ),
                          );
                        }
                    ),
                  ),
                  SizedBox(height: mw(27),),
                  Divider(color: Du.lightGrey(),thickness: mw(7),),
                  SizedBox(height: mw(12),),
                  Padding(
                    padding: EdgeInsets.only(left: mw(14)),
                    child: Text('상품 정보', style: Ts.h4bb(),),
                  ),
                  SizedBox(height: mw(13),),
                  Divider(color: Du.lightGrey(),thickness: mw(1),),
                ],
              ),
            ),
            SliverAppBar(
              key: tabKey,
              elevation: 1,
              automaticallyImplyLeading: false,
              pinned: true,
              flexibleSpace:PreferredSize(
                preferredSize: Size(double.infinity, mw(55)),
                child: ButtonsTabBar(
                  controller: _tabController,
                  backgroundColor: Du.primary(),
                  unselectedBackgroundColor: Du.lightGrey(),
                  labelStyle: Ts.bd1wr(),
                  unselectedLabelStyle: Ts.bd1br(),
                  borderWidth: 0,
                  borderColor: Du.primary(),
                  unselectedBorderColor: Du.lightGrey(),
                  radius: 100,
                  duration: 100,
                  labelSpacing: mw(5),
                  boxHeight: mw(40),
                  buttonMargin: EdgeInsets.fromLTRB(mw(14), mw(10), mw(0), mw(0)),
                  contentPadding: EdgeInsets.fromLTRB(mw(0), mw(5), mw(25), mw(5)),
                  tabs: tabs,
                ),
              ),
            ),
            SliverToBoxAdapter(
              child: _itemInfoBuild($purchase,img_url,$user),
            )
          ]
    );
 }

 Widget _itemInfoBuild($purchase,img_url,$user) {
    return SingleChildScrollView(
      physics:  ClampingScrollPhysics(),
      padding: EdgeInsets.fromLTRB(mw(0), mw(0), mw(0), mw(200)),
      child: Column(
        mainAxisAlignment: MainAxisAlignment.start,
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Container(
            padding: EdgeInsets.fromLTRB(mw(14), mw(20), mw(14), mw(27)),
            child: Stack(
              children: [
                Column(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.center,
                  children: <Widget>[
                    Text('운동할 때도 입고.일상에서도 입을 수 있는 레깅스.'),
                    SizedBox(height: mw(10),),
                    Text('아웃핏과 컬러매치, 핏을 중요하게 생각하는 저지만 레깅스라는 특성에 맞게 운동할때도 편해야 한다는 생각이 들었어요. 그래서 제가 찾은 사람은?'),

                    SizedBox(height: mw(20),),
                    Text('아웃핏과 컬러매치, 핏을 중요하게 생각하는 저지만 레깅스라는 특성에 맞게 운동할때도 편해야 한다는 생각이 들었어요. 그래서 제가 찾은 사람은?'),

                    SizedBox(height: mw(20),),
                    Text('아웃핏과 컬러매치, 핏을 중요하게 생각하는 저지만 레깅스라는 특성에 맞게 운동할때도 편해야 한다는 생각이 들었어요. 그래서 제가 찾은 사람은?'),

                    SizedBox(height: mw(20),),
                    Text('아웃핏과 컬러매치, 핏을 중요하게 생각하는 저지만 레깅스라는 특성에 맞게 운동할때도 편해야 한다는 생각이 들었어요. 그래서 제가 찾은 사람은?'),

                    _expand ? Column(
                      children: [
                        Placeholder(fallbackWidth: mw(332), fallbackHeight: mw(50),),
                        SizedBox(height: mw(20),),
                        Placeholder(fallbackWidth: mw(332), fallbackHeight: mw(50),),
                        SizedBox(height: mw(20),),
                        Placeholder(fallbackWidth: mw(332), fallbackHeight: mw(50),),
                        SizedBox(height: mw(20),),
                        Placeholder(fallbackWidth: mw(332), fallbackHeight: mw(50),),
                        SizedBox(height: mw(20),),
                        Placeholder(fallbackWidth: mw(332), fallbackHeight: mw(50),),
                        SizedBox(height: mw(20),),
                        Placeholder(fallbackWidth: mw(332), fallbackHeight: mw(50),),
                        SizedBox(height: mw(20),),
                        Placeholder(fallbackWidth: mw(332), fallbackHeight: mw(50),),
                        SizedBox(height: mw(20),),
                      ],
                    ): Container()

                  ],

                ),

                !_expand ? Positioned(
                  bottom: mw(0),
                  child: GestureDetector(
                    onTap: () {
                      setState(() {
                        _expand = true;
                      });
                    },
                    child: Container(
                      width: mw(332),
                      height: mw(45),
                      padding: EdgeInsets.fromLTRB(mw(115), mw(12), mw(98), mw(13)),
                      decoration: BoxDecoration(
                        color: Colors.white,
                        borderRadius: BorderRadius.all(Radius.circular(5)),
                        border: Border.all(color: Du.primary(), width: 2),
                        boxShadow: [
                        BoxShadow(
                          color: Colors.white,
                          offset: Offset(0.0, 20.0),
                          blurRadius: 40.0,
                          spreadRadius: 60.0,
                        ),
                      ],
                      ),
                      child: Row(
                          children: [
                            Text('상품정보 더보기', style: Ts.bd1pm(),),
                            SizedBox(width: mw(10),),
                            Icon(Icons.keyboard_arrow_down, color: Du.primary(), size: mw(20),),
                          ],
                        ),
                    ),
                  ),
                ): Container()

              ],
            ),
          ),

          Divider(color: Du.lightGrey(), thickness: mw(7),),
          InkWell(
            onTap: () {
              Navigator.push(context,MaterialPageRoute(builder: (context) => ItemQuestionPage(id:$purchase.neoitemId)));
            },
            child: Container(
              width: mw(360),
              height: mw(50),
              padding: EdgeInsets.fromLTRB(mw(14), mw(12), mw(14), mw(15)),
              child: Row(
                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                children: [
                  Row(
                    mainAxisAlignment: MainAxisAlignment.start,
                    children: [
                      Text('문의', style: Ts.h4bb(),),
                      Text('34', style: Ts.h4pb(),),
                    ],
                  ),
                  Icon(Icons.arrow_forward_ios, color: Colors.black, size: mw(15),)
                ],
              ),
            ),
          ),
          InkWell(
            onTap: () {
              Navigator.push(context,MaterialPageRoute(builder: (context) => BeforeOIPage()));
            },
            child: Container(
              width: mw(360),
              height: mw(50),
              padding: EdgeInsets.fromLTRB(mw(14), mw(12), mw(14), mw(15)),
              child: Row(
                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                children: [
                  Text('주문 정보', style: Ts.h4bb(),),
                  Icon(Icons.arrow_forward_ios, color: Colors.black, size: mw(15),)
                ],
              ),
            ),
          ),
          Divider(color: Du.lightGrey(), thickness: mw(7),),
          Padding(
            padding: EdgeInsets.fromLTRB(mw(14), mw(17), 0, mw(11)),
            child: Text('이 상품은 어때요?', style: Ts.h4bb(),),
          )

        ],
      ),
    );
 }



}

**Comment by Afonsocraposo** [comment]
@whatamelon please share the minimum amount of code to reproduce the error

**Comment by Afonsocraposo** [comment]
Close due to inactivity.
