### ISSUE TITLE
Update, buttons_tabbar: ^1.3.11, after that, the width of the buttons above is not controlled, and they are all on the left

### ISSUE THREAD

**Issue by xiongzhaoxu** [afonsocraposo/buttons_tabbar#56]
Update, buttons_tabbar: ^1.3.11, after that, the width of the buttons above is not controlled, and they are all on the left

**Comment by xiongzhaoxu** [comment]
![1719065815255](https://github.com/afonsocraposo/buttons_tabbar/assets/6897602/a7441196-f467-4526-a4ee-96fdd2cf1e0a)

**Comment by xiongzhaoxu** [comment]
I can only revert to 1.3.8 and continue to use

**Comment by afonsocraposo** [comment]
I'll investigate

**Comment by afonsocraposo** [comment]
@xiongzhaoxu from version 1.3.11 it's possible to choose the width of the tabs. If you set width as `null`, the tabs will fit their content. I'll release version 1.3.12 with this as the default behavior. If you want tabs to have a fixed width and center its content, you can set `contentCenter` to `true`
