### ISSUE TITLE
Close icon for web applications

### ISSUE THREAD

**Issue by postacik** [Afonsocraposo/buttons_tabbar#6]
Hi,
Thanks for this clean and useful package.

I want to use this package in a web dashboard where the user can add and delete tabs dynamically, like the ones in Google Chrome.

![image](https://user-images.githubusercontent.com/3977227/93184546-0bbd9780-f745-11ea-9030-aebf07e7054d.png)

Would it be possible to do the following with TabBarView and ButtonsTabBar?

1. Add a close icon on each tab and delete the tab bar item and its corresponding view when the icon is clicked.
2. Add a + icon to the right of the ButtonsTabBar as the last widget and call a callback handler which may be supplied as a parameter so that the user of the package can add a new tab in that handler.

Thanks :)

**Comment by Afonsocraposo** [comment]
Hi,
I don't know if it is possible or not.
If it's possible on the default Flutter tabs, it probably is with this plugin.
I didn't tested it, but feel free to do so!
