### ISSUE TITLE
Button margin not working properly

### ISSUE THREAD

**Issue by jlgarcia-vs** [afonsocraposo/buttons_tabbar#65]
# Bug Report
Problem with buttonMargin property.

## Description
I want to set the horizontal button margin to increase the space between buttons but when I change horizontal margin, the button increase in height. (see screenshots)

I've tested also with buttonMargin: EdgeInsets.only(left: 10.0, right: 10.0) with the same result.

## Expected Behavior
Increase only horizontal margin.

## Actual Behavior
With buttonMargin set:
![image](https://github.com/user-attachments/assets/4426a1c4-aec6-4e9a-b8a8-0632e866bcf5)

Without buttonMargin set:
![image](https://github.com/user-attachments/assets/c79d1ba3-0b2c-40fc-8b40-7b9fa7b81dd8)

## Code Example

```dart
           ButtonsTabBar(
              backgroundColor: Theme.of(context).colorScheme.onSecondaryFixedVariant,
              unselectedLabelStyle: TextStyle(color: Theme.of(context).colorScheme.onSecondaryFixedVariant),
              labelSpacing: 10.0,
              contentPadding: EdgeInsets.all(10.0),
              buttonMargin: EdgeInsets.symmetric(horizontal: 10.0),
              tabs: [
                Tab(text: 'Actual', icon: Icon(Icons.construction)),
                Tab(text: 'Último', icon: Icon(Icons.work_history))
              ],
            ),
```

**Please make sure to include a working example code that can reproduce the bug.** You can use the provided code snippet as a starting point.

Thank you for reporting this bug! We appreciate your contribution to improving our Flutter package.

**Comment by afonsocraposo** [comment]
Hey @jlgarcia-vs! Thank you very much for using the bug report template as intended 🙇 
This is the expected behavior. The default behavior 😄 The default value of `buttonMargin` is `EdgeInsets.all(4)`, so when you specify `EdgeInsets.symmetric(horizontal: 10.0)` it uses a 0 button margin vertically, thus allowing the button expand and fill the tab bar height.
You should be able to fix this by using `EdgeInsets.symmetric(horizontal: 10.0, vertical: 4.0)`.
Let me know if this fixes it

**Comment by jlgarcia-vs** [comment]
Hi @afonsocraposo, yes that's the solution.
Thank you very much for your help!!

This widget is a great job!
Regards

**Comment by afonsocraposo** [comment]
Happy to help!
Thank you very much for the kind words!

**Comment by afonsocraposo** [comment]
Happy to help!
Thank you very much for the kind words @jlgarcia-vs
