### ISSUE TITLE
TabController initial index not work

### ISSUE THREAD

**Issue by sleepingkit** [Afonsocraposo/buttons_tabbar#7]
Assign a TabController to ButtonsTabBar, but the TabController animateTo(1) and the TabController(initialIndex:1) is not working.
```
 TabController _tabController;
@override
  void initState() {
    _tabController = TabController(length: 2, vsync: this, initialIndex: 1);
    super.initState();
  }
...
 ButtonsTabBar(
                              controller: _tabController,
...
)
```

**Comment by Afonsocraposo** [comment]
Thank you for bringing this up!
I'll fix it as soon as possible

**Comment by Afonsocraposo** [comment]
@sleepingkit bug is fixed on commit https://github.com/Afonsocraposo/buttons_tabbar/commit/0d21b2c71710b63aee22cc45f7ac4d6d3af5783c.
To use the fixed version, update your `pubspec.yaml` to:
```yaml
dependencies:
  ...
  buttons_tabbar: ^1.0.1
```
